# Generated by Django 3.0.4 on 2020-04-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_no', models.IntegerField()),
                ('Emp_name', models.CharField(max_length=64)),
                ('Emp_sal', models.FloatField()),
                ('Emp_addr', models.CharField(max_length=64)),
            ],
        ),
    ]
